import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // This looks at the 'path' defined in config (../curriculum) 
  // and builds the sidebar based on folders
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;